### ISSUE TITLE
No parang file?

### ISSUE THREAD

**Issue by joolof** [avigan/VLTPF#99] opened 2022-01-12 15:42 UTC
Hi Arthur,
I had the same issue as Tomas on issue #91 and downloaded the new version of the pipeline. It can now go through the full reduction, but it looks like the "science_parang.fits" is no longer saved in the products directory.
Am I missing something?
Thanks for the hard work!
Johan

**Comment by avigan** [comment] 2022-01-18 09:55
@joolof I will look into that during the week. Thanks for raising the issue.

**Comment by joolof** [comment] 2022-01-18 17:49
Hi @avigan, in the end, I can also use `science_derot.fits`, and no longer have to account for the additional rotation afterwards, so feel free to close this issue if you think providing the `_parang` file is unnecessary.

**Comment by avigan** [comment] 2022-01-18 18:38
Ok, now I get it! This is related to commit b7ede41bf0b58430846720d29e73eaa1964ac9cf, which was pushed for version 1.4 of the pipeline. Before v1.4 I was saving both the _parang.fits files, which contains only the parallactic angles, and the _derot.fits file, which contains the proper values to use for derotation. This seemed confusing for non-advanced users, and I think there is only very few cases where someone would want to have the parallactic angles alone. I decided to save only the _derot.fits file starting from v1.4. 

I guess this is not documented properly enough. Maybe because there is no documentation :-D

Therefore I close the issue: it's not a bug, it's a feature :-p

**Closed as completed by avigan** 2022-01-18 18:38 UTC
